/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * module namespace wrapper
 * @const
 */
var tsickle_module_externs$test_files_export_as_namespace_export_as_namespace = {};
/** @const */
tsickle_module_externs$test_files_export_as_namespace_export_as_namespace.foo = {};
/**
 * @constructor
 * @struct
 */
tsickle_module_externs$test_files_export_as_namespace_export_as_namespace.foo.Bar = function() {};

/**
 * @return {void}
 */
tsickle_module_externs$test_files_export_as_namespace_export_as_namespace.foo.Bar.prototype.baz = function() {};

// export as namespace declaration handled at end of file
/** @const @suppress {duplicate} */
const exportNamespace = {};
/** @const @suppress {duplicate} */
exportNamespace.foo;

