/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * module namespace wrapper
 * @const
 */
var tsickle_module_externs$test_files_export_equals_namespace = {};

// export assignment handled via export as namespace

// export as namespace declaration handled at end of file
/** @const */
tsickle_module_externs$test_files_export_equals_namespace.SomeNamespace = {};
/**
 * @constructor
 * @struct
 */
tsickle_module_externs$test_files_export_equals_namespace.SomeNamespace.Clazz = function() {};
/** @const @suppress {duplicate} */
const SomeNamespace = {};
/** @const @suppress {duplicate} */
SomeNamespace.Clazz = tsickle_module_externs$test_files_export_equals_namespace.SomeNamespace.Clazz;

